/** Common LaTeX commands and environments for completions / coloring cues. */

export type CommandSnippet = {
  label: string;
  insertText: string;
  detail?: string;
};

export const COMMANDS: CommandSnippet[] = [
  { label: "\\documentclass", insertText: "\\documentclass[${1:options}]{${2:article}}", detail: "Document class" },
  { label: "\\usepackage", insertText: "\\usepackage{${1:package}}", detail: "Load package" },
  { label: "\\begin", insertText: "\\begin{${1:environment}}\n\t$0\n\\end{${1:environment}}", detail: "Begin environment" },
  { label: "\\end", insertText: "\\end{${1:environment}}", detail: "End environment" },
  { label: "\\section", insertText: "\\section{${1:title}}", detail: "Section" },
  { label: "\\subsection", insertText: "\\subsection{${1:title}}" },
  { label: "\\subsubsection", insertText: "\\subsubsection{${1:title}}" },
  { label: "\\paragraph", insertText: "\\paragraph{${1:title}}" },
  { label: "\\chapter", insertText: "\\chapter{${1:title}}" },
  { label: "\\title", insertText: "\\title{${1:title}}" },
  { label: "\\author", insertText: "\\author{${1:name}}" },
  { label: "\\date", insertText: "\\date{${1:\\today}}" },
  { label: "\\maketitle", insertText: "\\maketitle" },
  { label: "\\tableofcontents", insertText: "\\tableofcontents" },
  { label: "\\label", insertText: "\\label{${1:key}}" },
  { label: "\\ref", insertText: "\\ref{${1:key}}" },
  { label: "\\eqref", insertText: "\\eqref{${1:key}}" },
  { label: "\\cite", insertText: "\\cite{${1:key}}" },
  { label: "\\citep", insertText: "\\citep{${1:key}}" },
  { label: "\\footnote", insertText: "\\footnote{${1:text}}" },
  { label: "\\textbf", insertText: "\\textbf{${1:text}}", detail: "Bold" },
  { label: "\\textit", insertText: "\\textit{${1:text}}", detail: "Italic" },
  { label: "\\texttt", insertText: "\\texttt{${1:text}}", detail: "Monospace" },
  { label: "\\emph", insertText: "\\emph{${1:text}}" },
  { label: "\\underline", insertText: "\\underline{${1:text}}" },
  { label: "\\caption", insertText: "\\caption{${1:text}}" },
  { label: "\\includegraphics", insertText: "\\includegraphics[width=${1:0.8}\\linewidth]{${2:path}}" },
  { label: "\\item", insertText: "\\item ${1}" },
  { label: "\\hline", insertText: "\\hline" },
  { label: "\\newline", insertText: "\\newline" },
  { label: "\\newpage", insertText: "\\newpage" },
  { label: "\\clearpage", insertText: "\\clearpage" },
  { label: "\\hspace", insertText: "\\hspace{${1:1em}}" },
  { label: "\\vspace", insertText: "\\vspace{${1:1em}}" },
  { label: "\\frac", insertText: "\\frac{${1:num}}{${2:den}}", detail: "Fraction" },
  { label: "\\sqrt", insertText: "\\sqrt{${1:x}}" },
  { label: "\\sum", insertText: "\\sum_{${1:i=1}}^{${2:n}} ${3}" },
  { label: "\\int", insertText: "\\int_{${1:a}}^{${2:b}} ${3}\\,d${4:x}" },
  { label: "\\lim", insertText: "\\lim_{${1:x \\to 0}} ${2}" },
  { label: "\\left", insertText: "\\left${1:(} ${2} \\right${3:)}" },
  { label: "\\right", insertText: "\\right${1:)}" },
  { label: "\\mathbb", insertText: "\\mathbb{${1:R}}" },
  { label: "\\mathcal", insertText: "\\mathcal{${1:L}}" },
  { label: "\\mathrm", insertText: "\\mathrm{${1:text}}" },
  { label: "\\text", insertText: "\\text{${1:text}}" },
  { label: "\\alpha", insertText: "\\alpha" },
  { label: "\\beta", insertText: "\\beta" },
  { label: "\\gamma", insertText: "\\gamma" },
  { label: "\\delta", insertText: "\\delta" },
  { label: "\\epsilon", insertText: "\\epsilon" },
  { label: "\\theta", insertText: "\\theta" },
  { label: "\\lambda", insertText: "\\lambda" },
  { label: "\\mu", insertText: "\\mu" },
  { label: "\\pi", insertText: "\\pi" },
  { label: "\\sigma", insertText: "\\sigma" },
  { label: "\\phi", insertText: "\\phi" },
  { label: "\\omega", insertText: "\\omega" },
  { label: "\\infty", insertText: "\\infty" },
  { label: "\\partial", insertText: "\\partial" },
  { label: "\\cdot", insertText: "\\cdot" },
  { label: "\\times", insertText: "\\times" },
  { label: "\\pm", insertText: "\\pm" },
  { label: "\\leq", insertText: "\\leq" },
  { label: "\\geq", insertText: "\\geq" },
  { label: "\\neq", insertText: "\\neq" },
  { label: "\\approx", insertText: "\\approx" },
  { label: "\\rightarrow", insertText: "\\rightarrow" },
  { label: "\\Rightarrow", insertText: "\\Rightarrow" },
  { label: "\\in", insertText: "\\in" },
  { label: "\\subset", insertText: "\\subset" },
  { label: "\\forall", insertText: "\\forall" },
  { label: "\\exists", insertText: "\\exists" },
  { label: "\\bibliography", insertText: "\\bibliography{${1:references}}" },
  { label: "\\bibliographystyle", insertText: "\\bibliographystyle{${1:plain}}" },
  { label: "\\input", insertText: "\\input{${1:file}}" },
  { label: "\\include", insertText: "\\include{${1:file}}" },
  { label: "\\url", insertText: "\\url{${1:https://}}" },
  { label: "\\href", insertText: "\\href{${1:https://}}{${2:text}}" },
];

export const ENVIRONMENTS = [
  "document",
  "abstract",
  "figure",
  "figure*",
  "table",
  "table*",
  "equation",
  "equation*",
  "align",
  "align*",
  "gather",
  "gather*",
  "multline",
  "multline*",
  "itemize",
  "enumerate",
  "description",
  "center",
  "flushleft",
  "flushright",
  "quote",
  "quotation",
  "verbatim",
  "lstlisting",
  "minted",
  "tabular",
  "tabularx",
  "minipage",
  "theorem",
  "lemma",
  "proof",
  "definition",
  "example",
  "frame",
  "columns",
  "block",
];

export const SECTIONING = [
  "part",
  "chapter",
  "section",
  "subsection",
  "subsubsection",
  "paragraph",
  "subparagraph",
];
